name: BetterBosses
main: cooldogedev\BetterBosses\BetterBosses
author: cooldogedev
upgrade: Di4r, KienDev
version: 1.0.0
api: 5.0.0

permissions:
  betterbosses.manage:
    default: op
    description: "Permission to open boss panel"
